title: "Pookie's Digital Playground"
description: "Learning, Failing & Getting Better - My Journey into Python, Data Science & More!"
author: "Joseph"
baseurl: ""
url: "https://spacceddddd.github.io/Joe-s-Portfolio/"

theme: jekyll-theme-cayman

# Social links
social_links:
  github: Spacceddddd
  youtube: JJfrrrrrrrrrrrrr

# Build settings
markdown: kramdown
highlighter: rouge
